desc/apps/finance/api/urls.py
from django.urls import path, include
from rest_framework import routers
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from . import views

app_name = 'finance'

router = routers.DefaultRouter()
router.register('finance', views.ExpendViewSet)

urlpatterns = [
    path('expenses/', views.FinanceExpendListView.as_view(),name='finance_expend_list'),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
        # path('expense/', ExpenseSingle.as_view()),
    # path('expense/', ExpenseSingle.as_view()),
    path('', include(router.urls)),
]

desc/apps/finance/urls.py
from django.urls import path
from desc.apps.finance.views import *

urlpatterns = [
    path('', finance_listview, name='finance-list'),
    path('profit/', ProfitListView.as_view()),
    path('all/', all_finance_listview),
    path('stat/', FinanceStatisticView.as_view()),
    path('all(<int:page>+)/', all_finance_listview),
    path('create/', FinanceCreateView.as_view(), name='finance-create'),

    path('<int:pk>/update/', FinanceUpdateView.as_view(), name='finance-update'),
    path('<int:pk>/delete/', FinanceDeleteView.as_view(), name='finance-delete'),
    path('<int:pk>/', FinanceDetailView.as_view(), name='finance-detail'),


    # выборка по дате
    # path('date/$', finance_listview_date),
    path('date/', finance_listview_date_form, name='finance-date'),
    path('date/<int:year>/<int:month>/<int:date>/', finance_listview_date),
    path('search/', post_search, name='post_search'),

# Далее описание API
    # path('expenses/', Expenses.as_view()),
    # path('expense/', ExpenseSingle.as_view()),
    # path('expense/', ExpenseSingle.as_view()),
]

desc/urls.py
"""desc URL Configuration
"""
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from django.views.generic import RedirectView

from django.conf.urls.static import static

from django.views.generic import TemplateView
from django.urls import path, re_path, include

from wagtail.admin import urls as wagtailadmin_urls
from wagtail.documents import urls as wagtaildocs_urls
from wagtail.core import urls as wagtail_urls

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from desc.apps.finance.api.views import ExpendViewSet
# import debug_toolbar

from desc.apps.finance.views import (
    finance_listview,
    all_finance_listview,
    finance_listview_date,
    # finance_detailview,
    # finance_createview,
    FinanceCreateView,
    FinanceDetailView,
    FinanceUpdateView,
    FinanceDeleteView,
    ArifmView, Arifm2View, Arifm2classView, RussView, TrudView, DetsadView, GirlsView,
    HomeView,
    get_data, ChartData,

    # AllFinanceListView
)

# if settings.DEBUG:
#     import debug_toolbar
#
#     urlpatterns = [
#       url(r'^__debug__/', include(debug_toolbar.urls)),
#         ] + urlpatterns

from profit.views import ProfitListView

# TODO переписать по возможности на path

sitemaps = {'posts': PostSitemap,}


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^auto/', include('desc.apps.auto.urls')),

    path('arifmetika/', ArifmView.as_view(), name='arifmetika'),
    path('russ/', RussView.as_view(), name='russ'),
    path('girls/', GirlsView.as_view(), name='russ'),
    path('учебники/арифметика/', ArifmView.as_view(), name='arifmetika'),
    path('учебники/арифметика2/', Arifm2View.as_view(), name='arifmetika2'),
    path('учебники/арифметика2класс/', Arifm2classView.as_view(), name='arifmetika2class'),
    path('учебники/русский/', RussView.as_view(), name='russ'),
    path('учебники/труд-школьника/', TrudView.as_view(), name='trud1'),
    path('учебники/детсад/', DetsadView.as_view(), name='detsad'),
    path('api/data/', get_data, name='api-data'),
    path('api/chart/data/', ChartData.as_view()),

    path('finance/', include('desc.apps.finance.urls')),

    url(r'^profit/', include('profit.urls')),

    path('catalog/', include('catalog.urls')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    url(r'^accounts/', include('django.contrib.auth.urls')),

    re_path(r'^cms/', include(wagtailadmin_urls)),
    re_path(r'^documents/', include(wagtaildocs_urls)),
    path('api/', include('desc.apps.finance.api.urls', namespace='api')),

    re_path(r'', include(wagtail_urls)),
    # url(r'^__debug__/', include(debug_toolbar.urls)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#    import debug_toolbar
#    urlpatterns = [
#        url(r'^__debug__/', include(debug_toolbar.urls)),
#    ] + urlpatterns

desc/apps/finance/api/views.py
from rest_framework import generics
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import permissions
from rest_framework import viewsets
from ..models import FinanceExpend
from .serializers import FinanceExpendSerializer, ExpendSerializer


class FinanceExpendListView(generics.ListAPIView):
    queryset = FinanceExpend.objects.all()
    serializer_class = FinanceExpendSerializer

class ExpendViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = FinanceExpend.objects.all()
    serializer_class = ExpendSerializer

class Expenses(APIView):
    """ Список расходов общий """
    permission_classes = [permissions.AllowAny]
    def get(self, request):
        today = datetime.date.today()
        now_year = date(today, 'Y')

        # Расходы за этот месяц
        expenses_from_year = FinanceExpend.objects.filter(timestamp__year=now_year)

        expenses = expenses_from_year.order_by('-timestamp')[:30]
        # TODO EDIT THIS TO FILTER LIMIT

        # expenses = FinanceExpend.objects.all()
        serializer = ExpensesSerializers(expenses, many=True)
        return Response({"data": serializer.data})

class ExpenseSingle(APIView):
    """Одна запись расходов"""
    permission_classes = [permissions.AllowAny]
#     permission_classes = [permissions.IsAuthenticated]

    def get(self, request):
        id = request.GET.get("id")
        obj = FinanceExpend.objects.get(id=id)
        serializer = SingleSerializers(obj)
        return Response({"data": serializer.data})

desc/apps/finance/views.py
from django.db.models import Q
from django.contrib.auth import get_user_model
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, get_object_or_404
from django.views import View
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.db.models import Avg, Max, Sum
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.utils.translation import get_language, activate
from django.template.defaultfilters import date
from django.urls import reverse
from django.http import Http404
from django.utils.translation import ugettext_lazy as _

import datetime


from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import permissions

from django.contrib.postgres.search import SearchVector
from .forms import FinanceCreateForm, FinanceFilterSingleDateForm, SearchForm
from desc.apps.finance.models import FinanceExpend, FinanceProfit

from desc.apps.finance.serializers import (SingleSerializers, ExpensesSerializers)

from .mixins import AjaxFormMixin


class FinanceCreateView(AjaxFormMixin, CreateView):
    form_class = FinanceCreateForm
    template_name = 'finance/form.html'

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.owner = self.request.user
        instance.save()

        return super(FinanceCreateView, self).form_valid(form)


class FinanceUpdateView(AjaxFormMixin, UpdateView):
    form_class = FinanceCreateForm
    template_name = 'finance/form.html'

    def get_queryset(self):
        return FinanceExpend.objects.all()

    def get_context_data(self, *args, **kwargs):
        context = super(FinanceUpdateView, self).get_context_data(*args, **kwargs)
        context['title'] = 'Update Item'
        return context


class FinanceDeleteView(DeleteView):
    #model = FinanceExpend

   def delete(self, request, *args, **kwargs):
   #    self.object = self.get_object()

    success_url = '/finance/'


def handle_uploaded_file(f):
    with open('test.txt', 'wb+') as destination:
        for chunk in f.chunks():
            destination.write(chunk)


User = get_user_model()


class HomeView(View):
    def get(self, request, *args, **kwargs):
        template_name = 'home.html'
        context = {
            'customers': '10'
        }
        return render(request, template_name, context)

class ArifmView(View):
    def get(self, request, *args, **kwargs):
        template_name = 'arifmetika.html'
        context = { }
        return render(request, template_name, context)

class Arifm2View(View):
    def get(self, request, *args, **kwargs):
        template_name = 'arifmetika2.html'
        context = { }
        return render(request, template_name, context)

class Arifm2classView(View):
    def get(self, request, *args, **kwargs):
        template_name = 'arifmetika2class.html'
        context = { }
        return render(request, template_name, context)

class RussView(View):
    def get(self, request, *args, **kwargs):
        template_name = 'russ.html'
        context = { }
        return render(request, template_name, context)

class GirlsView(View):
    def get(self, request, *args, **kwargs):
        template_name = 'girls.html'
        context = { }
        return render(request, template_name, context)

class TrudView(View):
    def get(self, request, *args, **kwargs):
        template_name = 'trud1.html'
        context = { }
        return render(request, template_name, context)

class DetsadView(View):
    def get(self, request, *args, **kwargs):
        template_name = 'detsad.html'
        context = { }
        return render(request, template_name, context)


def get_data(request, *args, **kwargs):
    # ip = request.META['REMOTE_ADDR']
    data = {
        "sales": 100,
        "customers": 10
    }
    return JsonResponse(data)


class ChartData(APIView):
    authentication_classes = []
    permission_classes = []
    # TODO добавить finance profit

    def get(self, request, format=None):
        import datetime
        now = datetime.date.today()
        # текущий год
        now_year = now.year
        # прошлый год
        last_year = now.year - 1

        year = FinanceExpend.objects.filter(timestamp__year=now_year)
        data_last_year = FinanceExpend.objects.filter(timestamp__year=last_year)
        # новый массив со значениями за текущий год
        now_year_arr = []
        # новый массив со значениями за прошлый год
        last_year_arr = []
        # получим данные за 12 месяцев для каждого случая
        for x in range(1, 13):
            now_year_arr.append(year.filter(timestamp__month=x).aggregate(total=Sum('total'))['total'])
            last_year_arr.append(data_last_year.filter(timestamp__month=x).aggregate(total=Sum('total'))['total'])

        # qs_count = User.objects.all().count()
        # Заголовки для графика
        labels = [
            "Январь", "Февраль", "Март", "Апрель",
            "Май", "Июнь", "Июль", "Август", "Сентябрь",
            "Октябрь", "Ноябрь", "Декабрь"]

        data = {
            "labels": labels,
            "default": now_year_arr,
            "last_year": last_year_arr
        }
        return Response(data)


class FinanceDetailView(DetailView):
    queryset = FinanceExpend.objects.all()


def finance_detailview(request, id):
    template_name = 'finance/finance_detail.html'
    obj = FinanceExpend.objects.get(id=id)
    # print(obj)
    context = {
        "object": obj
    }
    return render(request, template_name, context)


class FinanceStatisticView(View):


    def get(self, request, *args, **kwargs):
        # данные за период отпуска
        q = FinanceExpend.objects.filter(timestamp__range=["2019-07-26", "2019-08-05"])
        sum = q.aggregate(Sum('total'))
        template_name = 'statistic.html'

        context = {
            "sum": sum
        }
        return render(request, template_name, context)


def finance_listview(request):
    # русский
    activate('ru')
    get_language()

    today = datetime.date.today()

    # Месяц числом
    numMonth = date(today, 'm')
    # Этот год числом
    now_year = date(today, 'Y')

    # расходы на автомобили (все) за всё время:
    all_auto = FinanceExpend.objects.filter(category='auto').aggregate(Sum('total'))

    # Этот год
    # последние 30 записей за этот год
    year = FinanceExpend.objects.filter(timestamp__year=now_year)
    # Расходы за этот месяц
    sum_today_month = year.filter(timestamp__month=numMonth)
    aggr_today = sum_today_month.aggregate(Sum('total'))
    year16 = FinanceExpend.objects.filter(timestamp__year=2016)
    year17 = FinanceExpend.objects.filter(timestamp__year=2017)
    year18 = FinanceExpend.objects.filter(timestamp__year=2018)
    year19 = FinanceExpend.objects.filter(timestamp__year=2019)
    year20 = FinanceExpend.objects.filter(timestamp__year=2020)
    year21 = FinanceExpend.objects.filter(timestamp__year=2021)
    month1 = year.filter(timestamp__month=1)
    month2 = year.filter(timestamp__month=2)
    month3 = year.filter(timestamp__month=3)
    month4 = year.filter(timestamp__month=4)
    month5 = year.filter(timestamp__month=5)
    month6 = year.filter(timestamp__month=6)
    month7 = year.filter(timestamp__month=7)
    month8 = year.filter(timestamp__month=8)
    month9 = year.filter(timestamp__month=9)
    month10 = year.filter(timestamp__month=10)
    month11 = year.filter(timestamp__month=11)
    month12 = year.filter(timestamp__month=12)

    month1_expend = month1.aggregate(Sum('total'))
    month2_expend = month2.aggregate(Sum('total'))
    month3_expend = month3.aggregate(Sum('total'))
    month4_expend = month4.aggregate(Sum('total'))
    month5_expend = month5.aggregate(Sum('total'))
    month6_expend = month6.aggregate(Sum('total'))
    month7_expend = month7.aggregate(Sum('total'))
    month8_expend = month8.aggregate(Sum('total'))
    month9_expend = month9.aggregate(Sum('total'))
    month10_expend = month10.aggregate(Sum('total'))
    month11_expend = month11.aggregate(Sum('total'))
    month12_expend = month12.aggregate(Sum('total'))

    all = FinanceExpend.objects.all()
    maximum = year.aggregate(Max('total'))
    queryset = year.order_by('-timestamp')[:30]
    total_sum = year.aggregate(Sum('total'))
    sum16 = year16.aggregate(Sum('total'))
    sum17 = year17.aggregate(Sum('total'))
    sum18 = year18.aggregate(Sum('total'))
    sum19 = year19.aggregate(Sum('total'))
    sum20 = year20.aggregate(Sum('total'))
    sum21 = year21.aggregate(Sum('total'))

    all_sum = all.aggregate(Sum('total'))
    # средний чек за весь период
    avg = FinanceExpend.objects.aggregate(total_avg=Avg('total'))

    context = {
        "object_list": queryset,
        "avg": avg,
        "maximum": maximum,
        "total": total_sum,
        "all_sum": all_sum,
        'sum16': sum16,
        'sum17': sum17,
        "sum18": sum18,
        "sum19": sum19,
        "sum20": sum20,
        "sum21": sum21,
        "numMonth": numMonth,
        "sumTodayMonth": aggr_today,
        'month1_expend': month1_expend,
        'month2_expend': month2_expend,
        'month3_expend': month3_expend,
        'month4_expend': month4_expend,
        'month5_expend': month5_expend,
        'month6_expend': month6_expend,
        'month7_expend': month7_expend,
        'month8_expend': month8_expend,
        'month9_expend': month9_expend,
        'month10_expend': month10_expend,
        'month11_expend': month11_expend,
        'month12_expend': month12_expend,
        'all_auto_expend': all_auto,
    }
    template_name = 'finance/finance_list.html'
    return render(request, template_name, context)


def finance_listview_auto(request, *args, **kwargs):
    #  Выборка по категории Авто
    template_name = 'finance/finance_list.html'
    # последние 30 записей за этот год

templates/finance/finance_list.html
{% extends "base.html" %}

{% block head_title %}{{ block.super }}{% endblock head_title %}
{% block content %}
<main role="main">

<div class="row">

<div class="col-md-6 col-xs-12">


<h1>Finance</h1>
    <p>Расходы за {% now "F" %}: {{ sumTodayMonth.total__sum|floatformat }}</p>
<hr>

    <p>Сумма расходов за {% now "Y" %} год: <b>{{ total.total__sum|floatformat }}</b> </p>
    <p>Расходы за 2021 год: {{ sum21.total__sum|floatformat }}</p>
    <p>Расходы за 2020 год: {{ sum20.total__sum|floatformat }}</p>
    <p>Расходы за 2019 год: {{ sum19.total__sum|floatformat }}</p>
    <p>Расходы за 2018 год: {{ sum18.total__sum|floatformat }}</p>
    <p>Расходы за 2017 год: {{ sum17.total__sum|floatformat }}</p>
    <p>Расходы за 2016 год: {{ sum16.total__sum|floatformat }}</p>
    <p>Сумма расходов за всё время: {{ all_sum.total__sum|floatformat }}</p>

    <p>
     Средний чек покупки за год: {{ avg.total_avg|floatformat }}
    </p>
    <p>
     Максимальный чек покупки за год: {{ maximum.total__max|floatformat }}
    </p>
    <p>Все расходы по категории Авто: {{ all_auto_expend.total__sum|floatformat }}</p>
    <p>Отдельно по автомобилям:</p>
    <p>Все расходы на Лада Веста: {{ vesta_all.total__sum|floatformat }}</p>
    <p>Все расходы на УАЗ Патриот: {{ patriot_all.total__sum|floatformat }}</p>
    </div>


    </div>


<h2>Последние записи</h2>
<ul>
    {% for obj in object_list %}
        <li>
            <a href=' {% url "finance-detail" pk=obj.pk %}  '>
            {{ obj.timestamp|date:"d.m.Y" }} |
            {{ obj.name }} |
            {{ obj.category }} |
            {{ obj.total }} |
            </a>
             <a href=' {% url "finance-update" pk=obj.pk %}  '><img class="edit-icon" src="/static/img/edit.svg"></a>
        </li>
    {% endfor %}
</ul>

<p>Январь: {{ month1_expend.total__sum|floatformat }}</p>
<p>Февраль: {{ month2_expend.total__sum|floatformat }}</p>
<p>Март: {{ month3_expend.total__sum|floatformat }}</p>
<p>Апрель: {{ month4_expend.total__sum|floatformat }}</p>
<p>Май: {{ month5_expend.total__sum|floatformat }}</p>
<p>Июнь: {{ month6_expend.total__sum|floatformat }}</p>
<p>Июль: {{ month7_expend.total__sum|floatformat }}</p>
<p>Август: {{ month8_expend.total__sum|floatformat }}</p>
<p>Сентябрь: {{ month9_expend.total__sum|floatformat }}</p>
<p>Октябрь: {{ month10_expend.total__sum|floatformat }}</p>
<p>Ноябрь: {{ month11_expend.total__sum|floatformat }}</p>
<p>Декабрь: {{ month12_expend.total__sum|floatformat }}</p>


</main>


{% endblock content %}

templates/finance/finance_list_all.html
{% extends "base.html" %}

{% block head_title %}{{ block.super }} - страница {{ object_list.number }}{% endblock head_title %}

{% block meta %}
{% if object_list.has_previous %}
<link rel="prev" href="/finance/all/?page={{ object_list.previous_page_number }}" />
{% endif %}
{% if object_list.has_next %}
<link rel="next" href="/finance/all/?page={{ object_list.next_page_number }}" />
{% endif %}
{% endblock meta%}


{% block content %}

<h2>Список расходов</h2>

    <div class="row">
        <a href="{% url "finance-date" %}">Выбор данных по календарю</a>
    </div>

<ul>
    {% for obj in object_list %}
        <li>
            {{ obj.timestamp|date:"d.m.Y" }}
            {{ obj.name }}
            {{ obj.category }}
            {{ obj.total }}
            <a href=' {% url "finance-update" pk=obj.pk %}  '><img class="edit-icon" src="/static/img/edit.svg"></a>
        </li>
    {% endfor %}
</ul>

<div class="pagination">
    <span class="step-links">
        {% if object_list.has_previous %}
            <a href="?page={{ object_list.previous_page_number }}">Сюда</a>
        {% endif %}

        <span class="current">
            Лист {{ object_list.number }} из {{ object_list.paginator.num_pages }}.
        </span>

        {% if object_list.has_next %}
            <a href="?page={{ object_list.next_page_number }}">Туда</a>
        {% endif %}
    </span>
</div>

{% endblock content %}

templates/finance/finance_listview_date_form.html
{% extends "base.html" %}

{% block head_title %}{{ block.super }} - страница {{ object_list.number }}{% endblock head_title %}

{% block meta %}
{% if object_list.has_previous %}
<link rel="prev" href="/finance/all/?page={{ object_list.previous_page_number }}" />
{% endif %}
{% if object_list.has_next %}
<link rel="next" href="/finance/all/?page={{ object_list.next_page_number }}" />
{% endif %}
{% endblock meta%}


{% block content %}

<h2>Список расходов</h2>

    <div class="row">
    <form action="" method="post">
         {% csrf_token %}
{#  <div class="form-group">#}
{#    <label for="FilterSingleDate">Выбираем дату</label>#}
{#    <input type="date" class="form-control" id="FilterSingleDate" aria-describedby="dateHelp" placeholder="Введите дату">#}
{#    <small id="dateHelp" class="form-text text-muted">Выбираем дату</small>#}
{#  </div>#}
{{ form }}
  <button type="submit" class="btn btn-primary">Выбрать</button>
</form>
    </div>

<ul>

</ul>



{% endblock content %}

templates/finance/financeexpend_detail.html
{% extends "base.html" %}
{% block head_title %}{{ block.super }}{% endblock head_title %}
{% block content %}


<h2>Покупка: {{ object.name }}</h2>

{{ object.timestamp}} <br>


 <span class="detail-total">Цена: {{object.total}}</span> <br>

    {% if "products" in object.category %}
<img class="detail-icon" title="продукты" src="/static/img/depositphotos_5140629-stock-photo-fresh-vegetables-fruits-and-other.jpg" alt="продукты" >
    {% endif %}
{% if "auto" in object.category  %}
<img class="detail-icon" src="/static/img/pumping-gas-need-premium-0001-720x720.jpg"/>
{% endif %}

{% if "health" in object.category %}
<img class="detail-icon" src="/static/img/health.png"/>
{% endif %}
{% if object.files.url in object.files.url %}
    <p>Файлы во вложении:</p>
   <a href="{{ object.files.url }}">{{ object.files.name}} {{ object.files.size|filesizeformat}} </a>
    {% endif %}

<a href=' {% url "finance-update" pk=object.pk %}  '><img class="edit-icon" title="Редактировать" src="/static/img/edit.svg"></a>

{% endblock content %}

templates/finance/financeexpend_list.html
{% extends "base.html" %}

{% block head_title %}{{ block.super }}{% endblock head_title %}
{% block content %}

<h1>Finance</h1>

<h2>Все записи</h2>
<ul>
    {% for obj in object_list %}
        <li>
            {{ obj.timestamp|date:"d.m.Y" }}
            {{ obj.name }}
            {{ obj.category }}
            {{ obj.total }}
        </li>
    {% endfor %}
</ul>



{% endblock content %}

templates/finance/form.html
{% extends "base.html" %}
{% block head_title %}Добавляем расходы | {{ block.super }}{% endblock head_title %}
{% block content %}

<div class="col-md-6">
    <h2>Запись расходов</h2>

    {% if form.errors.non_field_errors %}
        {{ form.errors.non_field_errors }}
    {% endif %}
    <div id="result"></div>
    <form class="my-ajax-form" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
        <div class="form-group">
          {{field}}
        </div>
        {% endfor %}
        <div class="row">
               <div class="col-md-5">
                 <input class='btn btn-success' name="save" type="submit" value="Записать" />
               </div>

                <div class="col-md-5">
                    <input class='btn btn-danger' type="submit" value="Удалить запись" />
                </div>
        </div>


    </form>
</div>

{% endblock content %}

templates/finance/home_page.html
{% extends "blog/base.html" %}
{% load wagtailcore_tags %}
{% block body_class %} template-homepage {% endblock %}
{% block head_title %}{{ block.super }}{% endblock head_title %}
{% block content %}

        <h1>{{ self.title }}</h1>

{% endblock content %}

templates/finance/search.html
{% block title %}
  Search
{% endblock %}

{% block content %}
  {% if query %}
  <h1>материалы содержащие "{{ query }}"</h1>
  <h3>
    {% with results.count as total_results %}Found{{ total_results }} result {{ total_results|pluralize }} {% endwith %}
  </h3>
{% for post in results %}
<h4> <a href="{{post.get_absolute_url}}">{{post.title}}</a></h4>

{{ post.body|truncatewords:5}}
{% empty %}
<p>Нет результатов на этот запрос</p>
{% endfor %}

<p><a href="{% url 'blog:post_search' %}">Искать ещё раз</a> </p>
{% else %}
<h1>Поиск в записях</h1>
<form class="" action="." method="get">
  {{form.as_p }}
  <input type="submit" name="" value="Искать">
</form>

  {% endif %}
{% endblock %}